In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression



In [2]:
inc=pd.read_csv('census income dataset.csv')
inc

1                  2       3            4   5                    6  \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                        7               8       9       10     11  12  13  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   14      15  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3       United-States   <=50K  
4                Cuba   <=50K  
...               ...     ...  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K  

[32561 rows x 15 columns]

In [3]:
inc.dropna(inplace=True)
inc

1                  2       3            4   5                    6  \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                        7               8       9       10     11  12  13  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   14      15  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3       United-States   <=50K  
4                Cuba   <=50K  
...               ...     ...  
32556   United-States   <=50K  
32557   United-States    >50K  
32558   United-States   <=50K  
32559   United-States   <=50K  
32560   United-States    >50K  

[32561 rows x 15 columns]

In [4]:
inc.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15'],
      dtype='object')

In [5]:
inc.dtypes

1      int64
2     object
3      int64
4     object
5      int64
6     object
7     object
8     object
9     object
10    object
11     int64
12     int64
13     int64
14    object
15    object
dtype: object

In [6]:
inc.isnull().sum()

1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [7]:
x=inc.iloc[ : ,0:14]
x

1                  2       3            4   5                    6  \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                        7               8       9       10     11  12  13  \
0            Adm-clerical   Not-in-family   White     Male   2174   0  40   
1         Exec-managerial         Husband   White     Male      0   0  13   
2       Handlers-cleaners   Not-in-family   White     Male      0   0  40   
3       Handlers-cleaners         Husband   Black     Male      0   0  40   
4          Prof-specialty            Wife   Black   Female      0   0  40   
...                   ...             ...     ...      ...    ...  ..  ..   
32556        Tech-support            Wife   White   Female      0   0  38   
32557   Machine-op-inspct         Husband   White     Male      0   0  40   
32558        Adm-clerical       Unmarried   White   Female      0   0  40   
32559        Adm-clerical       Own-child   White     Male      0   0  20   
32560     Exec-managerial            Wife   White   Female  15024   0  40   

                   14  
0       United-States  
1       United-States  
2       United-States  
3       United-States  
4                Cuba  
...               ...  
32556   United-States  
32557   United-States  
32558   United-States  
32559   United-States  
32560   United-States  

[32561 rows x 14 columns]

In [8]:
y=inc.iloc[ : , 14:15]
y

15
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 1 columns]

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x2=le.fit_transform(x['2'])
x4=le.fit_transform(x['4'])
x6=le.fit_transform(x['6'])
x7=le.fit_transform(x['7'])
x8=le.fit_transform(x['8'])
x9=le.fit_transform(x['9'])
x10=le.fit_transform(x['10'])
x14=le.fit_transform(x['14'])

x['2']=x2
x['4']=x4
x['6']=x6
x['7']=x7
x['8']=x8
x['9']=x9
x['10']=x10
x['14']=x14

x



1  2       3   4   5  6   7  8  9  10     11  12  13  14
0      39  7   77516   9  13  4   0  1  4   1   2174   0  40  39
1      50  6   83311   9  13  2   3  0  4   1      0   0  13  39
2      38  4  215646  11   9  0   5  1  4   1      0   0  40  39
3      53  4  234721   1   7  2   5  0  2   1      0   0  40  39
4      28  4  338409   9  13  2  10  5  2   0      0   0  40   4
...    .. ..     ...  ..  .. ..  .. .. ..  ..    ...  ..  ..  ..
32556  27  4  257302   7  12  2  13  5  4   0      0   0  38  39
32557  40  4  154374  11   9  2   6  0  4   1      0   0  40  39
32558  58  4  151910  11   9  6   0  4  4   0      0   0  40  39
32559  22  4  201490  11   9  4   0  3  4   1      0   0  20  39
32560  52  5  287927  11   9  2   3  5  4   0  15024   0  40  39

[32561 rows x 14 columns]

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=46)


In [11]:
x_train.shape

(22792, 14)

In [12]:
x_test.shape

(9769, 14)

In [13]:
y_train.shape

(22792, 1)

In [14]:
y_test.shape

(9769, 1)

In [15]:
lg=LogisticRegression()
lg.fit(x_train,y_train)
pred=lg.predict(x_test)
print(pred)
print('accuracyscore: ',accuracy_score(y_test,pred))
print('confusionmatrix: ',confusion_matrix(y_test,pred))
print('classification report: ', classification_report(y_test,pred))



[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' <=50K']
accuracyscore:  0.7943494728221927
confusionmatrix:  [[7047  364]
 [1645  713]]
classification report:                precision    recall  f1-score   support

       <=50K       0.81      0.95      0.88      7411
        >50K       0.66      0.30      0.42      2358

    accuracy                           0.79      9769
   macro avg       0.74      0.63      0.65      9769
weighted avg       0.77      0.79      0.76      9769



In [16]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
print(mnb.score(x_train,y_train))
predmnb=mnb.predict(x_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.7830817830817831
0.7823728119561879
[[7063  348]
 [1778  580]]
              precision    recall  f1-score   support

       <=50K       0.80      0.95      0.87      7411
        >50K       0.62      0.25      0.35      2358

    accuracy                           0.78      9769
   macro avg       0.71      0.60      0.61      9769
weighted avg       0.76      0.78      0.74      9769



In [17]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print(gnb.score(x_train,y_train))
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.795981045981046
0.7945542020677654
[[7024  387]
 [1620  738]]
              precision    recall  f1-score   support

       <=50K       0.81      0.95      0.87      7411
        >50K       0.66      0.31      0.42      2358

    accuracy                           0.79      9769
   macro avg       0.73      0.63      0.65      9769
weighted avg       0.77      0.79      0.77      9769



In [18]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
print(dtc.score(x_train,y_train))
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.999956124956125
0.8150271266250384
[[6483  928]
 [ 879 1479]]
              precision    recall  f1-score   support

       <=50K       0.88      0.87      0.88      7411
        >50K       0.61      0.63      0.62      2358

    accuracy                           0.82      9769
   macro avg       0.75      0.75      0.75      9769
weighted avg       0.82      0.82      0.82      9769



In [19]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
print(knn.score(x_train,y_train))
knnpred=knn.predict(x_test)
print(accuracy_score(y_test,knnpred))
print(confusion_matrix(y_test,knnpred))
print(classification_report(y_test,knnpred))


0.8340645840645841
0.7759238407206469
[[6851  560]
 [1629  729]]
              precision    recall  f1-score   support

       <=50K       0.81      0.92      0.86      7411
        >50K       0.57      0.31      0.40      2358

    accuracy                           0.78      9769
   macro avg       0.69      0.62      0.63      9769
weighted avg       0.75      0.78      0.75      9769



In [20]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

0.8599651960282526
[[6925  486]
 [ 882 1476]]
              precision    recall  f1-score   support

       <=50K       0.89      0.93      0.91      7411
        >50K       0.75      0.63      0.68      2358

    accuracy                           0.86      9769
   macro avg       0.82      0.78      0.80      9769
weighted avg       0.85      0.86      0.86      9769



In [21]:
from sklearn.ensemble import AdaBoostClassifier
ad=AdaBoostClassifier(n_estimators=100)
ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

0.8652881564131436
[[6988  423]
 [ 893 1465]]
              precision    recall  f1-score   support

       <=50K       0.89      0.94      0.91      7411
        >50K       0.78      0.62      0.69      2358

    accuracy                           0.87      9769
   macro avg       0.83      0.78      0.80      9769
weighted avg       0.86      0.87      0.86      9769



In [22]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x_train,y_train)
gb_pred=gb.predict(x_test)
print(accuracy_score(y_test,gb_pred))
print(confusion_matrix(y_test,gb_pred))
print(classification_report(y_test,gb_pred))

0.86539052103593
[[7029  382]
 [ 933 1425]]
              precision    recall  f1-score   support

       <=50K       0.88      0.95      0.91      7411
        >50K       0.79      0.60      0.68      2358

    accuracy                           0.87      9769
   macro avg       0.84      0.78      0.80      9769
weighted avg       0.86      0.87      0.86      9769



In [23]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

sv=SVC()
score=cross_val_score(sv,x,y,cv=5,scoring='accuracy')
print('acccuracy score= ',score)
print('mean scores= ',score.mean())
print('standard deviation= ',score.std())

y_pred=cross_val_predict(sv,x,y,cv=5)
conf_mat=confusion_matrix(y,y_pred)
print(conf_mat)
accuracy_score(y,y_pred)

acccuracy score=  [0.79563949 0.79407248 0.79514742 0.79699017 0.79422604]
mean scores=  0.7952151216372773
standard deviation=  0.0010601298420307285
[[24693    27]
 [ 6641  1200]]


0.7952151346703111

In [24]:
dtc=DecisionTreeClassifier(criterion='gini')
score=cross_val_score(dtc,x,y,cv=5,scoring='accuracy')
print('accuracy= ',score)
print('mean scores= ', score.mean())
print('standard deviation=',score.std())

y_pred=cross_val_predict(dtc,x,y,cv=5)
conf_mat=confusion_matrix(y,y_pred)
conf_mat
accuracy_score(y,y_pred)

accuracy=  [0.80684784 0.80512899 0.80912162 0.80804668 0.80912162]
mean scores=  0.8076533523389811
standard deviation= 0.001515755654437839


0.8077454623629495

In [25]:
# gradientboostingclassifier has the better accuracy score than other classifiers

In [26]:
from sklearn.externals import joblib
joblib.dump(gb,'gbsave.obj')
gb_from_joblib=joblib.load('gbsave.obj')
predict=gb.predict(x_test)
print(predict)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' <=50K']
