In [40]:
import pandas as pd
import numpy as np
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')





In [41]:
agri_train=pd.read_excel('train_agriculture.xlsx')
agri_train

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0     F00000001                      188          1          0   
1     F00000003                      209          1          0   
2     F00000004                      257          1          0   
3     F00000005                      257          1          1   
4     F00000006                      342          1          0   
...         ...                      ...        ...        ...   
4594  F00008078                     2138          0          1   
4595  F00008079                     2139          0          1   
4596  F00008080                     2267          0          1   
4597  F00008082                     2267          0          1   
4598  F00008083                     2267          0          1   

      Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                          1                  0                0.0   
1                          1                  0                0.0   
2                          1                  0                0.0   
3                          1                  0                0.0   
4                          1                  0                0.0   
...                      ...                ...                ...   
4594                       2                 20                NaN   
4595                       2                 30               47.0   
4596                       2                 10                7.0   
4597                       2                 10               20.0   
4598                       2                 10               33.0   

      Number_Weeks_Quit  Season  Crop_Damage  
0                     0       1            0  
1                     0       2            1  
2                     0       2            1  
3                     0       2            1  
4                     0       2            1  
...                 ...     ...          ...  
4594                  1       1            1  
4595                  2       1            1  
4596                 27       2            0  
4597                 24       2            0  
4598                 17       2            0  

[4599 rows x 10 columns]

In [42]:
agri_test=pd.read_excel('test_agriculture.xlsx')
agri_test

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0     F00000002                      188          1          1   
1     F00000007                      410          1          1   
2     F00000011                      626          1          0   
3     F00000013                      731          1          0   
4     F00000014                      789          0          0   
...         ...                      ...        ...        ...   
1194  F00003133                     1132          0          1   
1195  F00003135                     1132          0          1   
1196  F00003138                     1132          0          1   
1197  F00003149                     1212          0          1   
1198  F00003150                     1212          0          1   

      Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                          1                  0                NaN   
1                          1                  0                0.0   
2                          1                  0                0.0   
3                          1                  0                0.0   
4                          1                  0                0.0   
...                      ...                ...                ...   
1194                       2                 40               34.0   
1195                       2                 40               25.0   
1196                       2                 20               13.0   
1197                       2                 10               35.0   
1198                       2                 15                NaN   

      Number_Weeks_Quit  Season  
0                     0       2  
1                     0       2  
2                     0       2  
3                     0       2  
4                     0       1  
...                 ...     ...  
1194                  7       3  
1195                  3       1  
1196                 23       1  
1197                  5       1  
1198                 20       3  

[1199 rows x 9 columns]

In [43]:
agri_train.columns

Index(['ID', 'Estimated_Insects_Count', 'Crop_Type', 'Soil_Type',
       'Pesticide_Use_Category', 'Number_Doses_Week', 'Number_Weeks_Used',
       'Number_Weeks_Quit', 'Season', 'Crop_Damage'],
      dtype='object')

In [44]:
agri_train.drop('ID',axis=1,inplace=True)

In [45]:
agri_test.drop('ID',axis=1,inplace=True)

In [46]:
agri_train

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                         188          1          0                       1   
1                         209          1          0                       1   
2                         257          1          0                       1   
3                         257          1          1                       1   
4                         342          1          0                       1   
...                       ...        ...        ...                     ...   
4594                     2138          0          1                       2   
4595                     2139          0          1                       2   
4596                     2267          0          1                       2   
4597                     2267          0          1                       2   
4598                     2267          0          1                       2   

      Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                     0                0.0                  0       1   
1                     0                0.0                  0       2   
2                     0                0.0                  0       2   
3                     0                0.0                  0       2   
4                     0                0.0                  0       2   
...                 ...                ...                ...     ...   
4594                 20                NaN                  1       1   
4595                 30               47.0                  2       1   
4596                 10                7.0                 27       2   
4597                 10               20.0                 24       2   
4598                 10               33.0                 17       2   

      Crop_Damage  
0               0  
1               1  
2               1  
3               1  
4               1  
...           ...  
4594            1  
4595            1  
4596            0  
4597            0  
4598            0  

[4599 rows x 9 columns]

In [47]:
agri_train.isnull().sum()

Estimated_Insects_Count      0
Crop_Type                    0
Soil_Type                    0
Pesticide_Use_Category       0
Number_Doses_Week            0
Number_Weeks_Used          442
Number_Weeks_Quit            0
Season                       0
Crop_Damage                  0
dtype: int64

In [48]:
agri_test.isnull().sum()

Estimated_Insects_Count      0
Crop_Type                    0
Soil_Type                    0
Pesticide_Use_Category       0
Number_Doses_Week            0
Number_Weeks_Used          119
Number_Weeks_Quit            0
Season                       0
dtype: int64

In [49]:
agri_train.dropna(axis=0,inplace=True)

In [50]:
agri_test.dropna(axis=0,inplace=True)

In [51]:
agri_train.isna().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [52]:
agri_test.isna().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [53]:
x=agri_train.iloc[:, 0:8]

In [54]:
x

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                         188          1          0                       1   
1                         209          1          0                       1   
2                         257          1          0                       1   
3                         257          1          1                       1   
4                         342          1          0                       1   
...                       ...        ...        ...                     ...   
4593                     2138          0          1                       2   
4595                     2139          0          1                       2   
4596                     2267          0          1                       2   
4597                     2267          0          1                       2   
4598                     2267          0          1                       2   

      Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  
0                     0                0.0                  0       1  
1                     0                0.0                  0       2  
2                     0                0.0                  0       2  
3                     0                0.0                  0       2  
4                     0                0.0                  0       2  
...                 ...                ...                ...     ...  
4593                 60               47.0                  6       3  
4595                 30               47.0                  2       1  
4596                 10                7.0                 27       2  
4597                 10               20.0                 24       2  
4598                 10               33.0                 17       2  

[4157 rows x 8 columns]

In [55]:
y=agri_train.iloc[:,8:9]
y

Crop_Damage
0               0
1               1
2               1
3               1
4               1
...           ...
4593            0
4595            1
4596            0
4597            0
4598            0

[4157 rows x 1 columns]

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=46)


In [57]:
x_train.shape

(2909, 8)

In [58]:
x_test.shape

(1248, 8)

In [59]:
y_train.shape

(2909, 1)

In [60]:
y_test.shape

(1248, 1)

In [61]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
print(mnb.score(x_train,y_train))
predmnb=mnb.predict(x_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.6418013062908215
0.6209935897435898
[[713 203 118]
 [ 78  49  54]
 [ 13   7  13]]
              precision    recall  f1-score   support

           0       0.89      0.69      0.78      1034
           1       0.19      0.27      0.22       181
           2       0.07      0.39      0.12        33

    accuracy                           0.62      1248
   macro avg       0.38      0.45      0.37      1248
weighted avg       0.76      0.62      0.68      1248



In [62]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
print(dtc.score(x_train,y_train))
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.998281196287384
0.7419871794871795
[[875 137  22]
 [115  50  16]
 [ 21  11   1]]
              precision    recall  f1-score   support

           0       0.87      0.85      0.86      1034
           1       0.25      0.28      0.26       181
           2       0.03      0.03      0.03        33

    accuracy                           0.74      1248
   macro avg       0.38      0.38      0.38      1248
weighted avg       0.75      0.74      0.75      1248



In [63]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
print(knn.score(x_train,y_train))
knnpred=knn.predict(x_test)
print(accuracy_score(y_test,knnpred))
print(confusion_matrix(y_test,knnpred))
print(classification_report(y_test,knnpred))


0.854932966655208
0.811698717948718
[[990  42   2]
 [158  23   0]
 [ 28   5   0]]
              precision    recall  f1-score   support

           0       0.84      0.96      0.90      1034
           1       0.33      0.13      0.18       181
           2       0.00      0.00      0.00        33

    accuracy                           0.81      1248
   macro avg       0.39      0.36      0.36      1248
weighted avg       0.75      0.81      0.77      1248



In [64]:
def svmkernel(ker):
    svc=SVC(kernel=ker)
    svc.fit(x_train,y_train)
    print(svc.score(x_train,y_train))
    svcpred=svc.predict(x_test)
    print(accuracy_score(y_test,svcpred))
    print(confusion_matrix(y_test,svcpred))
    print(classification_report(y_test,svcpred))



In [65]:
svmkernel('rbf')

0.8356823650739086
0.8285256410256411
[[1034    0    0]
 [ 181    0    0]
 [  33    0    0]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91      1034
           1       0.00      0.00      0.00       181
           2       0.00      0.00      0.00        33

    accuracy                           0.83      1248
   macro avg       0.28      0.33      0.30      1248
weighted avg       0.69      0.83      0.75      1248



In [66]:
svmkernel('poly')

0.8356823650739086
0.8285256410256411
[[1034    0    0]
 [ 181    0    0]
 [  33    0    0]]
              precision    recall  f1-score   support

           0       0.83      1.00      0.91      1034
           1       0.00      0.00      0.00       181
           2       0.00      0.00      0.00        33

    accuracy                           0.83      1248
   macro avg       0.28      0.33      0.30      1248
weighted avg       0.69      0.83      0.75      1248



In [67]:
from sklearn.ensemble import AdaBoostClassifier
ad=AdaBoostClassifier(n_estimators=100)
ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

0.8349358974358975
[[1016   17    1]
 [ 152   25    4]
 [  26    6    1]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91      1034
           1       0.52      0.14      0.22       181
           2       0.17      0.03      0.05        33

    accuracy                           0.83      1248
   macro avg       0.51      0.38      0.39      1248
weighted avg       0.78      0.83      0.79      1248



In [68]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

0.8365384615384616
[[1001   33    0]
 [ 133   43    5]
 [  26    7    0]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91      1034
           1       0.52      0.24      0.33       181
           2       0.00      0.00      0.00        33

    accuracy                           0.84      1248
   macro avg       0.46      0.40      0.41      1248
weighted avg       0.79      0.84      0.80      1248



In [69]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x_train,y_train)
gb_pred=gb.predict(x_test)
print(accuracy_score(y_test,gb_pred))
print(confusion_matrix(y_test,gb_pred))
print(classification_report(y_test,gb_pred))

0.8341346153846154
[[1012   20    2]
 [ 151   29    1]
 [  26    7    0]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.91      1034
           1       0.52      0.16      0.24       181
           2       0.00      0.00      0.00        33

    accuracy                           0.83      1248
   macro avg       0.46      0.38      0.39      1248
weighted avg       0.78      0.83      0.79      1248



In [70]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict


In [71]:
mnb=MultinomialNB()
score=cross_val_score(mnb,x,y,cv=5)
print('score: ',score)
print('mean score: ',score.mean())
print('standard deviation: ',score.std())

y_pred=cross_val_predict(mnb,x,y,cv=5)
print('y prediction values')
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
conf_mat
accuracy_score(y,y_pred)

score:  [0.51442308 0.74639423 0.59807461 0.54873646 0.71961492]
mean score:  0.6254486600944181
standard deviation:  0.09214759467833844
y prediction values
[0 0 1 ... 0 1 1]


0.6254510464277123

In [72]:
sv=SVC()
score=cross_val_score(sv,x,y,cv=5,scoring='accuracy')
print('acccuracy score= ',score)
print('mean scores= ',score.mean())
print('standard deviation= ',score.std())

y_pred=cross_val_predict(sv,x,y,cv=5)
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
print(conf_mat)
accuracy_score(y,y_pred)

acccuracy score=  [0.83293269 0.83293269 0.83393502 0.83393502 0.83393502]
mean scores=  0.8335340877534018
standard deviation=  0.0004910373252073276
[0 0 0 ... 0 0 0]
[[3465    0    0]
 [ 588    0    0]
 [ 104    0    0]]


0.8335337984123166

In [73]:
dtc=DecisionTreeClassifier(criterion='gini')
score=cross_val_score(dtc,x,y,cv=5,scoring='accuracy')
print('f1-macro= ',score)
print('mean scores= ', score.mean())
print('standard deviation=',score.std())

y_pred=cross_val_predict(dtc,x,y,cv=5)
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
print(conf_mat)
accuracy_score(y,y_pred)

f1-macro=  [0.65504808 0.74399038 0.69915764 0.7087846  0.76534296]
mean scores=  0.7144647320188836
standard deviation= 0.038097947804430085
[1 1 1 ... 0 1 0]
[[2817  542  106]
 [ 391  152   45]
 [  73   26    5]]


0.7154197738753909

In [74]:
knn=KNeighborsClassifier()   
score=cross_val_score(knn,x,y,cv=10,scoring='accuracy')
print('Accuracy score: ',score)
print('mean scores: ', score.mean())
print('standard deviation: ',score.std())

y_pred=cross_val_predict(knn,x,y,cv=5)
print(y_pred)
conf_mat=confusion_matrix(y,y_pred)
print(conf_mat)
accuracy_score(y,y_pred)

Accuracy score:  [0.79086538 0.82932692 0.80288462 0.83653846 0.81730769 0.80288462
 0.80528846 0.82650602 0.77831325 0.82891566]
mean scores:  0.8118831093605191
standard deviation:  0.017943388229034716
[0 0 0 ... 0 0 0]
[[3332  130    3]
 [ 515   72    1]
 [  92   12    0]]


0.8188597546307433

In [75]:
#RandomForestClassifier has more accuracy score compared to other models

In [77]:
from sklearn.externals import joblib
joblib.dump(rf,'rffile.obj')
rf_from_joblib=joblib.load('rffile.obj')
predict=rf.predict(agri_test)
print(predict)

[1 1 1 ... 0 0 0]
