In [73]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')



In [40]:
flights_train=pd.read_excel('Data_Train.xlsx')
flights_train

Airline Date_of_Journey    Source Destination  \
0           IndiGo      24/03/2019  Banglore   New Delhi   
1        Air India       1/05/2019   Kolkata    Banglore   
2      Jet Airways       9/06/2019     Delhi      Cochin   
3           IndiGo      12/05/2019   Kolkata    Banglore   
4           IndiGo      01/03/2019  Banglore   New Delhi   
...            ...             ...       ...         ...   
10678     Air Asia       9/04/2019   Kolkata    Banglore   
10679    Air India      27/04/2019   Kolkata    Banglore   
10680  Jet Airways      27/04/2019  Banglore       Delhi   
10681      Vistara      01/03/2019  Banglore   New Delhi   
10682    Air India       9/05/2019     Delhi      Cochin   

                       Route Dep_Time  Arrival_Time Duration Total_Stops  \
0                  BLR → DEL    22:20  01:10 22 Mar   2h 50m    non-stop   
1      CCU → IXR → BBI → BLR    05:50         13:15   7h 25m     2 stops   
2      DEL → LKO → BOM → COK    09:25  04:25 10 Jun      19h     2 stops   
3            CCU → NAG → BLR    18:05         23:30   5h 25m      1 stop   
4            BLR → NAG → DEL    16:50         21:35   4h 45m      1 stop   
...                      ...      ...           ...      ...         ...   
10678              CCU → BLR    19:55         22:25   2h 30m    non-stop   
10679              CCU → BLR    20:45         23:20   2h 35m    non-stop   
10680              BLR → DEL    08:20         11:20       3h    non-stop   
10681              BLR → DEL    11:30         14:10   2h 40m    non-stop   
10682  DEL → GOI → BOM → COK    10:55         19:15   8h 20m     2 stops   

      Additional_Info  Price  
0             No info   3897  
1             No info   7662  
2             No info  13882  
3             No info   6218  
4             No info  13302  
...               ...    ...  
10678         No info   4107  
10679         No info   4145  
10680         No info   7229  
10681         No info  12648  
10682         No info  11753  

[10683 rows x 11 columns]

In [41]:
flights_test=pd.read_excel('Test_set.xlsx')
flights_test

Airline Date_of_Journey    Source Destination  \
0           Jet Airways       6/06/2019     Delhi      Cochin   
1                IndiGo      12/05/2019   Kolkata    Banglore   
2           Jet Airways      21/05/2019     Delhi      Cochin   
3     Multiple carriers      21/05/2019     Delhi      Cochin   
4              Air Asia      24/06/2019  Banglore       Delhi   
...                 ...             ...       ...         ...   
2666          Air India       6/06/2019   Kolkata    Banglore   
2667             IndiGo      27/03/2019   Kolkata    Banglore   
2668        Jet Airways       6/03/2019     Delhi      Cochin   
2669          Air India       6/03/2019     Delhi      Cochin   
2670  Multiple carriers      15/06/2019     Delhi      Cochin   

                Route Dep_Time  Arrival_Time Duration Total_Stops  \
0     DEL → BOM → COK    17:30  04:25 07 Jun  10h 55m      1 stop   
1     CCU → MAA → BLR    06:20         10:20       4h      1 stop   
2     DEL → BOM → COK    19:15  19:00 22 May  23h 45m      1 stop   
3     DEL → BOM → COK    08:00         21:00      13h      1 stop   
4           BLR → DEL    23:55  02:45 25 Jun   2h 50m    non-stop   
...               ...      ...           ...      ...         ...   
2666  CCU → DEL → BLR    20:30  20:25 07 Jun  23h 55m      1 stop   
2667        CCU → BLR    14:20         16:55   2h 35m    non-stop   
2668  DEL → BOM → COK    21:50  04:25 07 Mar   6h 35m      1 stop   
2669  DEL → BOM → COK    04:00         19:15  15h 15m      1 stop   
2670  DEL → BOM → COK    04:55         19:15  14h 20m      1 stop   

                  Additional_Info  
0                         No info  
1                         No info  
2     In-flight meal not included  
3                         No info  
4                         No info  
...                           ...  
2666                      No info  
2667                      No info  
2668                      No info  
2669                      No info  
2670                      No info  

[2671 rows x 10 columns]

In [57]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Airline=le.fit_transform(flights_train['Airline'])
Source=le.fit_transform(flights_train['Source'])
Destination=le.fit_transform(flights_train['Destination'])
Route=le.fit_transform(flights_train['Route'])
Total_Stops=le.fit_transform(flights_train['Total_Stops'])
Additional_Info=le.fit_transform(flights_train['Additional_Info'])
Dep_Time=le.fit_transform(flights_train['Dep_Time'])
Arrival_Time=le.fit_transform(flights_train['Arrival_Time'])
Duration=le.fit_transform(flights_train['Duration'])
Date_of_Journey=le.fit_transform(flights_train['Date_of_Journey'])

flights_train['Airline']=Airline
flights_train['Source']=Source
flights_train['Destination']=Destination
flights_train['Route']=Route
flights_train['Total_Stops']=Total_Stops
flights_train['Additional_Info']=Additional_Info
flights_train['Dep_Time']=Dep_Time
flights_train['Arrival_Time']=Arrival_Time
flights_train['Duration']=Duration
flights_train['Date_of_Journey']=Date_of_Journey


In [58]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Airline=le.fit_transform(flights_test['Airline'])
Source=le.fit_transform(flights_test['Source'])
Destination=le.fit_transform(flights_test['Destination'])
Route=le.fit_transform(flights_test['Route'])
Total_Stops=le.fit_transform(flights_test['Total_Stops'])
Additional_Info=le.fit_transform(flights_test['Additional_Info'])
Dep_Time=le.fit_transform(flights_test['Dep_Time'])
Arrival_Time=le.fit_transform(flights_test['Arrival_Time'])
Duration=le.fit_transform(flights_test['Duration'])
Date_of_Journey=le.fit_transform(flights_test['Date_of_Journey'])

flights_test['Airline']=Airline
flights_test['Source']=Source
flights_test['Destination']=Destination
flights_test['Route']=Route
flights_test['Total_Stops']=Total_Stops
flights_test['Additional_Info']=Additional_Info
flights_test['Dep_Time']=Dep_Time
flights_test['Arrival_Time']=Arrival_Time
flights_test['Duration']=Duration
flights_test['Date_of_Journey']=Date_of_Journey





In [59]:
flights_train

Airline  Date_of_Journey  Source  Destination  Route  Dep_Time  \
0            3               24       0            5     18       211   
1            1                6       3            0     84        31   
2            4               43       2            1    118        70   
3            3               10       3            0     91       164   
4            3                0       0            5     29       149   
...        ...              ...     ...          ...    ...       ...   
10678        0               41       3            0     64       183   
10679        1               29       3            0     64       193   
10680        4               29       0            2     18        58   
10681       10                0       0            5     18        92   
10682        1               42       2            1    108        85   

       Arrival_Time  Duration  Total_Stops  Additional_Info  Price  
0               233       240            4                8   3897  
1               906       336            1                8   7662  
2               413       106            1                8  13882  
3              1324       311            0                8   6218  
4              1237       303            0                8  13302  
...             ...       ...          ...              ...    ...  
10678          1259       236            4                8   4107  
10679          1305       237            4                8   4145  
10680           824       280            4                8   7229  
10681           938       238            4                8  12648  
10682          1124       347            1                8  11753  

[10682 rows x 11 columns]

In [60]:
flights_train.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [61]:
flights_train.dropna(inplace=True)

In [62]:
flights_train.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [63]:
flights_test.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
dtype: int64

In [64]:
x=flights_train.iloc[:,0:10]

In [65]:
x

Airline  Date_of_Journey  Source  Destination  Route  Dep_Time  \
0            3               24       0            5     18       211   
1            1                6       3            0     84        31   
2            4               43       2            1    118        70   
3            3               10       3            0     91       164   
4            3                0       0            5     29       149   
...        ...              ...     ...          ...    ...       ...   
10678        0               41       3            0     64       183   
10679        1               29       3            0     64       193   
10680        4               29       0            2     18        58   
10681       10                0       0            5     18        92   
10682        1               42       2            1    108        85   

       Arrival_Time  Duration  Total_Stops  Additional_Info  
0               233       240            4                8  
1               906       336            1                8  
2               413       106            1                8  
3              1324       311            0                8  
4              1237       303            0                8  
...             ...       ...          ...              ...  
10678          1259       236            4                8  
10679          1305       237            4                8  
10680           824       280            4                8  
10681           938       238            4                8  
10682          1124       347            1                8  

[10682 rows x 10 columns]

In [66]:
y=flights_train.iloc[:,10:11]
y

Price
0       3897
1       7662
2      13882
3       6218
4      13302
...      ...
10678   4107
10679   4145
10680   7229
10681  12648
10682  11753

[10682 rows x 1 columns]

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=45)

In [68]:
x_train.shape

(7156, 10)

In [69]:
y_train.shape

(7156, 1)

In [70]:
x_test.shape

(3526, 10)

In [71]:
y_test.shape

(3526, 1)

In [75]:
lr=LinearRegression()
lr.fit(x_train,y_train)
pred=lr.predict(x_test)
print(pred)
print("score: ",lr.score(x_train,y_train))
print('Mean absolute error: ',mean_absolute_error(y_test,pred))
print('Mean squared error:  ',mean_squared_error(y_test,pred))
print('Root mean squared error: ',np.sqrt(mean_squared_error(y_test,pred)))
print('r2score: ',r2_score(y_test,pred))

[[ 5579.55884761]
 [11297.12908286]
 [ 5755.88577629]
 ...
 [10418.33932794]
 [11360.95921125]
 [ 6755.31223242]]
score:  0.3588002373138791
Mean absolute error:  2690.7006675480757
Mean squared error:   14508551.474045731
Root mean squared error:  3809.0092509792794
r2score:  0.34590023768115896


In [76]:
ls=Lasso(alpha=0.01)
ls.fit(x_train,y_train)
ls.score(x_train,y_train)

0.3588002373012992

In [77]:
rd=Ridge(alpha=0.01)              
rd.fit(x_train,y_train)
rd.score(x_train,y_train)

0.3588002373137601

In [78]:
from sklearn.linear_model import ElasticNet
enr=ElasticNet(alpha=0.01)
enr.fit(x_train,y_train)
enrpred=enr.predict(x_test)
print(enr.score(x_train,y_train))
enr.coef_


0.3587987171506771


array([-2.90480573e+01, -7.99239109e+00, -3.10369189e+02,  2.09826850e+02,
       -4.84169081e+00,  3.05850150e+00, -4.06859139e-01, -2.36695705e+00,
       -1.59709947e+03,  1.15273192e+02])

In [84]:
from sklearn.model_selection import cross_val_score,cross_val_predict
lmc=LinearRegression()
lmscore=cross_val_score(lmc,x,y,cv=10)
print(lmscore)
print(lmscore.mean())
pred=cross_val_predict(lmc,x,y,cv=10)
pred


[0.35769867 0.35414887 0.33135457 0.39846035 0.38694871 0.34359686
 0.36766844 0.34479399 0.36061513 0.3021112 ]
0.3547396784387368


array([[7256.11532389],
       [8886.49824572],
       [9701.03001847],
       ...,
       [5685.85265775],
       [6618.97161361],
       [9050.66639491]])

In [86]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=10,random_state=45)
rf.fit(x_train,y_train)
rf.score(x_train,y_train)

0.9703569705125826

In [87]:
#RandomForestRegressor has better score than other models

In [88]:
from sklearn.externals import joblib
joblib.dump(rf,'rffile.obj')
rf_joblib=joblib.load('rffile.obj')
predict=rf_joblib.predict(x_test)
print(predict)

[ 3753.6 11046.7  7386.4 ... 10525.6  9731.5 11786.1]
