In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression



In [4]:
lp=pd.read_csv('loan prediction.csv')
lp

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [5]:
lp.dropna(inplace=True)
lp

Loan_ID  Gender Married Dependents     Education Self_Employed  \
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[480 rows x 13 columns]

In [6]:
lp.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [38]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Loan_ID=le.fit_transform(lp['Loan_ID'])
Gender=le.fit_transform(lp['Gender'])
Dependents=le.fit_transform(lp['Dependents'])
Married=le.fit_transform(lp['Married'])
Education=le.fit_transform(lp['Education'])
Self_Employed=le.fit_transform(lp['Self_Employed'])
Property_Area=le.fit_transform(lp['Property_Area'])
Loan_Status=le.fit_transform(lp['Loan_Status'])


lp['Loan_ID']=Loan_ID
lp['Gender']=Gender
lp['Dependents']=Dependents
lp['Married']=Married
lp['Education']=Education
lp['Self_Employed']=Self_Employed
lp['Property_Area']=Property_Area
lp['Loan_Status']=Loan_Status



In [39]:
lp

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
1          0       1        1           1          0              0   
2          1       1        1           0          0              1   
3          2       1        1           0          1              0   
4          3       1        0           0          0              0   
5          4       1        1           2          0              1   
..       ...     ...      ...         ...        ...            ...   
609      475       0        0           0          0              0   
610      476       1        1           3          0              0   
611      477       1        1           1          0              0   
612      478       1        1           2          0              0   
613      479       0        0           0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History  Property_Area  Loan_Status  
1               1.0              0            0  
2               1.0              2            1  
3               1.0              2            1  
4               1.0              2            1  
5               1.0              2            1  
..              ...            ...          ...  
609             1.0              0            1  
610             1.0              0            1  
611             1.0              2            1  
612             1.0              2            1  
613             0.0              1            0  

[480 rows x 13 columns]

In [40]:
x=lp.iloc[:,0:12]

In [41]:
x

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
1          0       1        1           1          0              0   
2          1       1        1           0          0              1   
3          2       1        1           0          1              0   
4          3       1        0           0          0              0   
5          4       1        1           2          0              1   
..       ...     ...      ...         ...        ...            ...   
609      475       0        0           0          0              0   
610      476       1        1           3          0              0   
611      477       1        1           1          0              0   
612      478       1        1           2          0              0   
613      479       0        0           0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History  Property_Area  
1               1.0              0  
2               1.0              2  
3               1.0              2  
4               1.0              2  
5               1.0              2  
..              ...            ...  
609             1.0              0  
610             1.0              0  
611             1.0              2  
612             1.0              2  
613             0.0              1  

[480 rows x 12 columns]

In [42]:
y=lp.iloc[:,12:]

In [43]:
y

Loan_Status
1              0
2              1
3              1
4              1
5              1
..           ...
609            1
610            1
611            1
612            1
613            0

[480 rows x 1 columns]

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=46)


In [45]:
x_train.shape

(336, 12)

In [46]:
x_test.shape

(144, 12)

In [47]:
y_train.shape

(336, 1)

In [48]:
y_test.shape

(144, 1)

In [49]:
lg=LogisticRegression()
lg.fit(x_train,y_train)
pred=lg.predict(x_test)
print(pred)
print('accuracyscore: ',accuracy_score(y_test,pred))
print('confusionmatrix: ',confusion_matrix(y_test,pred))
print('classification report: ', classification_report(y_test,pred))



[1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0
 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 1]
accuracyscore:  0.8263888888888888
confusionmatrix:  [[20 23]
 [ 2 99]]
classification report:                precision    recall  f1-score   support

           0       0.91      0.47      0.62        43
           1       0.81      0.98      0.89       101

    accuracy                           0.83       144
   macro avg       0.86      0.72      0.75       144
weighted avg       0.84      0.83      0.81       144



In [50]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
print(mnb.score(x_train,y_train))
predmnb=mnb.predict(x_test)
print(accuracy_score(y_test,predmnb))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.5119047619047619
0.4722222222222222
[[17 26]
 [50 51]]
              precision    recall  f1-score   support

           0       0.25      0.40      0.31        43
           1       0.66      0.50      0.57       101

    accuracy                           0.47       144
   macro avg       0.46      0.45      0.44       144
weighted avg       0.54      0.47      0.49       144



In [51]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)
print(gnb.score(x_train,y_train))
predgnb=gnb.predict(x_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.7976190476190477
0.8125
[[22 21]
 [ 6 95]]
              precision    recall  f1-score   support

           0       0.79      0.51      0.62        43
           1       0.82      0.94      0.88       101

    accuracy                           0.81       144
   macro avg       0.80      0.73      0.75       144
weighted avg       0.81      0.81      0.80       144



In [52]:
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
print(dtc.score(x_train,y_train))
preddtc=dtc.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

1.0
0.7361111111111112
[[24 19]
 [19 82]]
              precision    recall  f1-score   support

           0       0.56      0.56      0.56        43
           1       0.81      0.81      0.81       101

    accuracy                           0.74       144
   macro avg       0.69      0.69      0.69       144
weighted avg       0.74      0.74      0.74       144



In [53]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
print(knn.score(x_train,y_train))
knnpred=knn.predict(x_test)
print(accuracy_score(y_test,knnpred))
print(confusion_matrix(y_test,knnpred))
print(classification_report(y_test,knnpred))


0.7410714285714286
0.6527777777777778
[[ 8 35]
 [15 86]]
              precision    recall  f1-score   support

           0       0.35      0.19      0.24        43
           1       0.71      0.85      0.77       101

    accuracy                           0.65       144
   macro avg       0.53      0.52      0.51       144
weighted avg       0.60      0.65      0.62       144



In [54]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

0.8194444444444444
[[24 19]
 [ 7 94]]
              precision    recall  f1-score   support

           0       0.77      0.56      0.65        43
           1       0.83      0.93      0.88       101

    accuracy                           0.82       144
   macro avg       0.80      0.74      0.76       144
weighted avg       0.81      0.82      0.81       144



In [55]:
from sklearn.ensemble import AdaBoostClassifier
ad=AdaBoostClassifier(n_estimators=100)
ad.fit(x_train,y_train)
ad_pred=ad.predict(x_test)
print(accuracy_score(y_test,ad_pred))
print(confusion_matrix(y_test,ad_pred))
print(classification_report(y_test,ad_pred))

0.7291666666666666
[[21 22]
 [17 84]]
              precision    recall  f1-score   support

           0       0.55      0.49      0.52        43
           1       0.79      0.83      0.81       101

    accuracy                           0.73       144
   macro avg       0.67      0.66      0.67       144
weighted avg       0.72      0.73      0.72       144



In [56]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(x_train,y_train)
gb_pred=gb.predict(x_test)
print(accuracy_score(y_test,gb_pred))
print(confusion_matrix(y_test,gb_pred))
print(classification_report(y_test,gb_pred))

0.7986111111111112
[[22 21]
 [ 8 93]]
              precision    recall  f1-score   support

           0       0.73      0.51      0.60        43
           1       0.82      0.92      0.87       101

    accuracy                           0.80       144
   macro avg       0.77      0.72      0.73       144
weighted avg       0.79      0.80      0.79       144



In [57]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

sv=SVC()
score=cross_val_score(sv,x,y,cv=5,scoring='accuracy')
print('acccuracy score= ',score)
print('mean scores= ',score.mean())
print('standard deviation= ',score.std())

y_pred=cross_val_predict(sv,x,y,cv=5)
conf_mat=confusion_matrix(y,y_pred)
print(conf_mat)
accuracy_score(y,y_pred)

acccuracy score=  [0.6875     0.6875     0.6875     0.69791667 0.69791667]
mean scores=  0.6916666666666667
standard deviation=  0.00510310363079827
[[  0 148]
 [  0 332]]


0.6916666666666667

In [58]:
dtc=DecisionTreeClassifier(criterion='gini')
score=cross_val_score(dtc,x,y,cv=5,scoring='accuracy')
print('accuracy= ',score)
print('mean scores= ', score.mean())
print('standard deviation=',score.std())

y_pred=cross_val_predict(dtc,x,y,cv=5)
conf_mat=confusion_matrix(y,y_pred)
conf_mat
accuracy_score(y,y_pred)

accuracy=  [0.66666667 0.59375    0.72916667 0.77083333 0.70833333]
mean scores=  0.69375
standard deviation= 0.06023680122833734


0.7020833333333333

In [60]:
#Logistic Regression has the better accuracy_score compared with other models ..

In [61]:
from sklearn.externals import joblib
joblib.dump(lg,'lgsave.obj')
lg_from_joblib=joblib.load('lgsave.obj')
predict=lg.predict(x_test)
print(predict)

[1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0
 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 0 1 1 0 0 1]
