In [120]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')



In [121]:
fee=pd.read_excel('fee_Train.xlsx')
fee

Qualification  Experience  Rating  \
0              BHMSandMDinHomeopathy          24   100.0   
1        BAMSandMDinAyurvedaMedicine          12    98.0   
2     MBBSandMSinOtorhinolaryngology           9     NaN   
3                BScinZoologyandBAMS          12     NaN   
4                               BAMS          20   100.0   
...                              ...         ...     ...   
5956                  MBBSandMSinENT          19    98.0   
5957                            MBBS          33     NaN   
5958                            MBBS          41    97.0   
5959      MBBSandMDinGeneralMedicine          15    90.0   
5960         BDSandMDSinOrthodontics          17   100.0   

                             Place          Profile  \
0             KakkanadandErnakulam        Homeopath   
1           WhitefieldandBangalore         Ayurveda   
2       MathikereinBELandBangalore    ENTSpecialist   
3     BannerghattaRoadandBangalore         Ayurveda   
4           KeelkattalaiandChennai         Ayurveda   
...                            ...              ...   
5956      BasavanagudiandBangalore    ENTSpecialist   
5957        NungambakkamandChennai  GeneralMedicine   
5958   GreaterKailashPart2andDelhi  GeneralMedicine   
5959        VileparleWestandMumbai  GeneralMedicine   
5960             PitampuraandDelhi          Dentist   

                                     Miscellaneous_Info  Fees  
0                     10016FeedbackKakkanadandErnakulam   100  
1                    9876FeedbackWhitefieldandBangalore   350  
2                                                   NaN   300  
3     BannerghattaRoadandBangalore₹250AvailableonSun...   250  
4                    1004FeedbackKeelkattalaiandChennai   250  
...                                                 ...   ...  
5956               9845FeedbackBasavanagudiandBangalore   300  
5957                                                NaN   100  
5958            9711FeedbackGreaterKailashPart2andDelhi   600  
5959  GeneralMedicalConsultationViralFeverTreatmentI...   100  
5960  AcrylicPartialDentureCrownsandBridgesFixingArt...   200  

[5961 rows x 7 columns]

In [122]:
fee.isnull().sum()

Qualification            0
Experience               0
Rating                3302
Place                   25
Profile                  0
Miscellaneous_Info    2620
Fees                     0
dtype: int64

In [123]:
fee.drop(['Miscellaneous_Info'],axis=1,inplace=True)

In [124]:
fee['Rating'].fillna(fee['Rating'].mean(),inplace=True)

In [125]:
fee.isnull().sum()

Qualification     0
Experience        0
Rating            0
Place            25
Profile           0
Fees              0
dtype: int64

In [126]:
fee.dropna(axis=0,inplace=True)

In [127]:
fee.isna().sum()

Qualification    0
Experience       0
Rating           0
Place            0
Profile          0
Fees             0
dtype: int64

In [128]:
fee

Qualification  Experience      Rating  \
0              BHMSandMDinHomeopathy          24  100.000000   
1        BAMSandMDinAyurvedaMedicine          12   98.000000   
2     MBBSandMSinOtorhinolaryngology           9   94.643475   
3                BScinZoologyandBAMS          12   94.643475   
4                               BAMS          20  100.000000   
...                              ...         ...         ...   
5956                  MBBSandMSinENT          19   98.000000   
5957                            MBBS          33   94.643475   
5958                            MBBS          41   97.000000   
5959      MBBSandMDinGeneralMedicine          15   90.000000   
5960         BDSandMDSinOrthodontics          17  100.000000   

                             Place          Profile  Fees  
0             KakkanadandErnakulam        Homeopath   100  
1           WhitefieldandBangalore         Ayurveda   350  
2       MathikereinBELandBangalore    ENTSpecialist   300  
3     BannerghattaRoadandBangalore         Ayurveda   250  
4           KeelkattalaiandChennai         Ayurveda   250  
...                            ...              ...   ...  
5956      BasavanagudiandBangalore    ENTSpecialist   300  
5957        NungambakkamandChennai  GeneralMedicine   100  
5958   GreaterKailashPart2andDelhi  GeneralMedicine   600  
5959        VileparleWestandMumbai  GeneralMedicine   100  
5960             PitampuraandDelhi          Dentist   200  

[5936 rows x 6 columns]

In [129]:
fee.drop(['Qualification'],axis=1,inplace=True)

In [130]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Place=le.fit_transform(fee['Place'])
Profile=le.fit_transform(fee['Profile'])


fee['Place']=Place
fee['Profile']=Profile

In [131]:
fee

Experience      Rating  Place  Profile  Fees
0             24  100.000000    299        5   100
1             12   98.000000    866        0   350
2              9   94.643475    457        3   300
3             12   94.643475     68        0   250
4             20  100.000000    337        0   250
...          ...         ...    ...      ...   ...
5956          19   98.000000     70        3   300
5957          33   94.643475    541        4   100
5958          41   97.000000    216        4   600
5959          15   90.000000    850        4   100
5960          17  100.000000    603        1   200

[5936 rows x 5 columns]

In [132]:
x=fee.iloc[:,0:4]
x

Experience      Rating  Place  Profile
0             24  100.000000    299        5
1             12   98.000000    866        0
2              9   94.643475    457        3
3             12   94.643475     68        0
4             20  100.000000    337        0
...          ...         ...    ...      ...
5956          19   98.000000     70        3
5957          33   94.643475    541        4
5958          41   97.000000    216        4
5959          15   90.000000    850        4
5960          17  100.000000    603        1

[5936 rows x 4 columns]

In [133]:
y=fee.iloc[:,4:5]
y

Fees
0      100
1      350
2      300
3      250
4      250
...    ...
5956   300
5957   100
5958   600
5959   100
5960   200

[5936 rows x 1 columns]

In [134]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=45)

In [135]:
x_train.shape

(3977, 4)

In [136]:
y_train.shape

(3977, 1)

In [137]:
x_test.shape

(1959, 4)

In [138]:
y_test.shape

(1959, 1)

In [139]:
lr=LinearRegression()
lr.fit(x_train,y_train)
pred=lr.predict(x_test)
print(pred)
print("score: ",lr.score(x_train,y_train))
print('Mean absolute error: ',mean_absolute_error(y_test,pred))
print('Mean squared error:  ',mean_squared_error(y_test,pred))
print('Root mean squared error: ',np.sqrt(mean_squared_error(y_test,pred)))
print('r2score: ',r2_score(y_test,pred))

[[288.01818726]
 [281.38437031]
 [302.05705612]
 ...
 [358.15248211]
 [327.29648165]
 [285.41005166]]
score:  0.02943162287128409
Mean absolute error:  153.67900044872607
Mean squared error:   34776.06723507424
Root mean squared error:  186.48342348604135
r2score:  0.03628019468649113


In [140]:
from sklearn.linear_model import Lasso,Ridge
ls=Lasso(alpha=0.01)
ls.fit(x_train,y_train)
ls.score(x_train,y_train)

0.029431621679191115

In [141]:
rd=Ridge(alpha=0.01)              
rd.fit(x_train,y_train)
rd.score(x_train,y_train)

0.029431622871267882

In [142]:
from sklearn.linear_model import ElasticNet
enr=ElasticNet(alpha=0.01)
enr.fit(x_train,y_train)
enrpred=enr.predict(x_test)
print(enr.score(x_train,y_train))
enr.coef_


0.029431550012252727


array([-0.89679413, -3.04482461, -0.03906558, 15.71133468])

In [143]:
from sklearn.model_selection import cross_val_score,cross_val_predict
lmc=LinearRegression()
lmscore=cross_val_score(lmc,x,y,cv=10)
print(lmscore)
print(lmscore.mean())
pred=cross_val_predict(lmc,x,y,cv=10)
pred


[0.00364697 0.01623833 0.05285754 0.02696782 0.02398477 0.04733908
 0.02563227 0.02314795 0.05064996 0.01340729]
0.028387198617701847


array([[337.60049978],
       [239.36376389],
       [323.67495678],
       ...,
       [318.27794417],
       [334.710732  ],
       [261.57743867]])

In [144]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=10,random_state=45)
rf.fit(x_train,y_train)
rf.score(x_train,y_train)

0.8214163477319809

In [145]:
# random forest has more score than other models

In [146]:
from sklearn.externals import joblib
joblib.dump(rf,'rffile.obj')
rf_joblib=joblib.load('rffile.obj')
predict=rf_joblib.predict(x_test)
print(predict)

[275. 155. 560. ... 216. 470.  71.]
